### ISSUE TITLE
Questions on Ignite Go Client 

### ISSUE THREAD

**Issue by ceshihao** [amsokol/ignite-go-client#1]
@amsokol 

Is this repo for a V2 [amsokol/go-ignite-client](https://github.com/amsokol/go-ignite-client)?
Or any other difference in your plan?

**Comment by amsokol** [comment]
Hi @ceshihao 

It's new client for Apache Ignite v2.4+.
New binary protocol has been issued in Apache Ignite v2.4.
This new golang client is using this one.
I'm developing golang client using this specification:
https://apacheignite.readme.io/docs/binary-client-protocol
I add sql driver over binary protocol also.

Next task (it will be ignite-javascript-client repo) is to develop JavaScript/TypeScript client.
