### ISSUE TITLE
error go get 

### ISSUE THREAD

**Issue by tbeaudouin05** [amsokol/ignite-go-client#14]
Hello amsokol,

How are you?

I get this error when I try to pull the package with go get :

"go get -u github.com/amsokol/ignite-go-client
go build github.com/amsokol/ignite-go-client: no non-test Go files in /home/tbeaudouin03/go/src/github.com/amsokol/ignite-go-client"

**Comment by philippgille** [comment]
I think it worked for me, but with `github.com/amsokol/ignite-go-client` not all required subpackages (like `"github.com/amsokol/ignite-go-client/binary/v1"`) are downloaded anyway, so try this one: `go get -u github.com/amsokol/ignite-go-client/...`.

**Comment by amsokol** [comment]
Hi @tbeaudouin05, @philippgille,

Thanks for this issue.
I added empty examples.go file to fix this warning.
