### ISSUE TITLE
bug multiple insert / merge?

### ISSUE THREAD

**Issue by tbeaudouin05** [amsokol/ignite-go-client#21]
I may be doing something wrong but this below returns this error: failed to execute query: [1] Failed to execute DML statement [stmt=MERGE INTO PUBLIC.TASK(ID_TASK, ID_HERO, CREATED_AT, UPDATED_AT, TITLE) VALUES (?,?,?,?,?), (?,?,?,?,?), params=[item.id, i113811807988213595940, 2018-12-09T07:25:20.000Z, 2018-12-09T07:25:20.000Z, item.title, item.id2, i113811807988213595940, 2018-12-09T07:25:20.000Z, 2018-12-09T07:25:20.000Z, item.title]]

"ctx := context.Background()
	db := ignite.IgniteConnect(ctx)
	defer db.Close()

	stmtStr := `MERGE INTO PUBLIC.TASK(ID_TASK, ID_HERO, CREATED_AT, UPDATED_AT, TITLE) VALUES (?,?,?,?,?), (?,?,?,?,?)`
	args := make([]interface{}, 10)
	args[0] = `item.id`
	args[1] = `i113811807988213595940`
	args[2] = `2018-12-09T07:25:20.000Z`
	args[3] = `2018-12-09T07:25:20.000Z`
	args[4] = `item.title`
	args[5] = `item.id2`
	args[6] = `i113811807988213595940`
	args[7] = `2018-12-09T07:25:20.000Z`
	args[8] = `2018-12-09T07:25:20.000Z`
	args[9] = `item.title`

	// insert using prepare statement
	stmt, err := db.PrepareContext(c, stmtStr)
	if err != nil {
		log.Printf("failed to prepare statement: %v", err)
	}

	_, err = stmt.ExecContext(c, args...)
	if err != nil {
		log.Printf("failed sql execute: %v", err)
	}"

on the other hand, when we only have one set of arguments, there is no error and the merge works well:
"ctx := context.Background()
	db := ignite.IgniteConnect(ctx)
	defer db.Close()

	stmtStr := `MERGE INTO PUBLIC.TASK(ID_TASK, ID_HERO, CREATED_AT, UPDATED_AT, TITLE) VALUES (?,?,?,?,?)`
	args := make([]interface{}, 5)
	args[0] = `item.id`
	args[1] = `i113811807988213595940`
	args[2] = `2018-12-09T07:25:20.000Z`
	args[3] = `2018-12-09T07:25:20.000Z`
	args[4] = `item.title`

	// insert using prepare statement
	stmt, err := db.PrepareContext(c, stmtStr)
	if err != nil {
		log.Printf("failed to prepare statement: %v", err)
	}

	_, err = stmt.ExecContext(c, args...)
	if err != nil {
		log.Printf("failed sql execute: %v", err)
	}
"
any clue? :)

**Comment by tbeaudouin05** [comment]
My bad, actually it works - it was some other weird bug linked to the data format of my inputs

**Comment by amsokol** [comment]
Hi. Cool. I close this issue.
